services:
  - type: web
    name: planetary-zenith-app
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server
    plan: free
    autoDeploy: true